#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

FROM registry.access.redhat.com/ubi8/python-39@sha256:10f349e7819b561bf86fd0b828b28457f5a5a4a4958b68a961085dbb1ad123a9

EXPOSE 8080

RUN pip install httpx starlette sse_starlette uvicorn

COPY python /app/python
COPY static /app/static

WORKDIR /app

CMD ["python", "python/main.py"]
