name: container image build

on: workflow_dispatch

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USERN: ${{ github.actor }}
  REGISTRY_USERP: ${{ secrets.GITHUB_TOKEN }}

jobs: 
  build-and-push:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write

    steps:
    - name: checkout repository
      uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

    - name: Log in to ghcr.io
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USERN }}
        password: ${{ env.REGISTRY_USERP }}

    - name: build and push frontend (fedora)
      uses: docker/build-push-action@9472e9021074a3cb3279ba431598b8836d40433f
      with:
        context: ./frontend
        file: ./frontend/Containerfile
        push: true
        tags: ${{ env.IMAGE_REGISTRY }}/frontend:${{ github.sha }}

    - name: build and push backend (fedora)
      uses: docker/build-push-action@9472e9021074a3cb3279ba431598b8836d40433f
      with: 
        context: ./backend
        file: ./backend/Containerfile
        push: true
        tags: ${{ env.IMAGE_REGISTRY }}/backend:${{ github.sha }}

    - name: build and push frontend (ubi)
      uses: docker/build-push-action@9472e9021074a3cb3279ba431598b8836d40433f
      with:
        context: ./frontend
        file: ./frontend/Containerfile-ubi
        push: true
        tags: ${{ env.IMAGE_REGISTRY }}/frontend-ubi:${{ github.sha }}

    - name: build and push backend (ubi)
      uses: docker/build-push-action@9472e9021074a3cb3279ba431598b8836d40433f
      with:
        context: ./backend
        file: ./backend/Containerfile-ubi
        push: true
        tags: ${{ env.IMAGE_REGISTRY }}/backend-ubi:${{ github.sha }}